### ISSUE TITLE
how do I download the War3Evo sound pack?

### ISSUE THREAD

**Issue by SkayZerA** [War3Evo/War3Source-EVO#15]
how do I download the War3Evo sound pack? link is off
from: https://forums.alliedmods.net/showthread.php?t=284415

**Comment by War3Evo** [comment]
I should probably revise that as those servers no longer exist.

**Comment by War3Evo** [comment]
You'll have to figure out how to download it from GitHub branch: https://github.com/War3Evo/War3Source-EVO/tree/sound-pack
