### ISSUE TITLE
Clear instructions on how to install CSGO server

### ISSUE THREAD

**Issue by You-Honey** [War3Evo/War3Source-EVO#39]
Would it be possible to get clear instructions how to install this mod on CSGO server?

I find the wiki really confusing.

**Comment by War3Evo** [comment]
Most people would have to hunt for all the information that is on the Wiki.  Your lucky that there's so much information, your overwhelmed.   It's better to be more information than not enough!

I put it in top down order on setting it up.  First, Second, Third.

Information is based on a Linux server installation.  If your doing Windows, best of luck to you.  I've never used a Windows server.

Order of install:

> Create Your steam server game account first!
> Install SteamCMD
> install MetaMod
> install SourceMod
> install War3Source-EVO
> Configure your server and War3Source-EVO
> Start your server

Have any questions, please use the discussion tab.

**Comment by War3Evo** [comment]
If you already have your CSGO server with SourceMod installed, you can just grab the latest compiled version from https://forums.alliedmods.net/showpost.php?p=2430764&postcount=1

You can then put the appropriate files from the archive where they go.

Edit the cfg/warsource_csgo.cfg

and there you go.

**Comment by War3Evo** [comment]
Installing a server for SourceMod has always been confusing the first time and documentations it there you've got to read.

It's really hard to tell what knowledge someone brings to the table when they go to the wiki to install the server.  It's really hard to create a documentation for every single individual person with different needs.

Your more than welcome to explain how the wiki could be improved.

**Comment by You-Honey** [comment]
I'm a developer and while I have a lot of experience on hosting stuff I have never hosted a CSGO server so comments like these:

```
Install SteamCMD
install MetaMod
install SourceMod
install War3Source-EVO
```

Are really hard to interpret. What would help people like me would be an example on how to install all of those in some of the most common environment such as Ubuntu.

**Comment by War3Evo** [comment]
I'm right now working on a Android Studio open source project that will automatically install everything needed for a SourceMod server for a Linux based server.

It will also eventually handle installing other plugins from SourceMod, other than my own.

Until then, I could possibly write a installation script (.sh) file that would install a CSGO server from scratch with everything installed.  Then you just follow the prompts during the installation.

**Comment by War3Evo** [comment]
Here's an easy to use install script:  [https://github.com/War3Evo/War3Source-EVO/blob/master/installcsgo.sh](https://github.com/War3Evo/War3Source-EVO/blob/master/installcsgo.sh)

I've tested it myself in Debian 11.  It should work in Ubuntu because Debian is the mother of Ubuntu.

**Comment by War3Evo** [comment]
I was able to create install scripts for CSS, CSGO, TF2, and FOF.

[https://github.com/War3Evo/War3Source-EVO](url)

I'll see about creating update scripts tomorrow.

**Comment by You-Honey** [comment]
@War3Evo First of all: thank you! You've done a beautiful job.

Few last issues remaining. When I run `/home/hlserver/startCSGO.sh` I get this error: `Cannot exec '/home/hlserver/csgo/srcds_run': No such file or directory`

How should I proceed?

**Comment by War3Evo** [comment]
Did you have at least 50 GB of space for the installation?
you can type df-h
`df -h`

**Comment by You-Honey** [comment]
The disk is big enough but it doesn't seem to use that much:

```
root@csgo-war3:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           198M  980K  197M   1% /run
/dev/vda1        49G  1.9G   47G   4% /
tmpfs           988M     0  988M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/vda15      105M  5.3M  100M   5% /boot/efi
tmpfs           198M  4.0K  198M   1% /run/user/0
```

**Comment by War3Evo** [comment]
Create a SUDO user, delete however, then install using a SUDO user.

**Comment by You-Honey** [comment]
Same result: `Cannot exec '/home/csgo/hlserver/csgo/srcds_run': No such file or directory`.

Here are the full logs:
[result.txt](https://github.com/War3Evo/War3Source-EVO/files/10853870/result.txt)

**Comment by War3Evo** [comment]
If your not on debian 11, then you might need more libraries for your Linux OS.

**Comment by You-Honey** [comment]
I'm on Ubuntu. I can switch to Debian though.

**Comment by War3Evo** [comment]
I'm looking thru all the libraries in the list and revising them.

It seems to stop installing libraries at the first sign of error.

**Comment by War3Evo** [comment]
debian@debian:~/Desktop$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by You-Honey** [comment]
I'm running it now. It seems to do way more things.

I'll report back after 15 min or so when it has finished downloading.

**Comment by War3Evo** [comment]
/home/csgo/hlserver/steamcmd.sh: line 37: /home/csgo/hlserver/linux32/steamcmd: No such file or directory

^^ that line is important... I had many issues with it last night..

I had to use bash -c to get it to run it.

**Comment by War3Evo** [comment]
Let me know if it was the updated file that helped or if you added a library?  if you did add a library, please let me know so I can add that library to the shell file.

**Comment by You-Honey** [comment]
This time it went much better. Here's the current errors:

```
/home/csgo/hlserver/csgo/srcds_run: 32: pushd: not found
/home/csgo/hlserver/csgo/srcds_run: 35: popd: not found
Server will auto-restart if there is a crash.
Updating server using Steam.
----------------------------
/home/csgo/hlserver/csgo/srcds_run: 1: eval: ./steam.sh: not found
----------------------------
LD_LIBRARY_PATH=/home/csgo/hlserver/csgo/bin:/home/csgo/hlserver/csgo:/home/csgo/hlserver/csgo/bin:
Failed to open libtier0.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
Add "-debug" to the /home/csgo/hlserver/csgo/srcds_run command line to generate a debug.log to help with solving this problem
Tue Feb 28 19:58:02 UTC 2023: Server restart in 10 seconds
Updating server using Steam.
----------------------------
/home/csgo/hlserver/csgo/srcds_run: 1: eval: ./steam.sh: not found
----------------------------
LD_LIBRARY_PATH=/home/csgo/hlserver/csgo/bin:/home/csgo/hlserver/csgo:/home/csgo/hlserver/csgo/bin:
Failed to open libtier0.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
Add "-debug" to the /home/csgo/hlserver/csgo/srcds_run command line to generate a debug.log to help with solving this problem
Tue Feb 28 19:58:12 UTC 2023: Server restart in 10 seconds
Updating server using Steam.
----------------------------
/home/csgo/hlserver/csgo/srcds_run: 1: eval: ./steam.sh: not found
----------------------------
LD_LIBRARY_PATH=/home/csgo/hlserver/csgo/bin:/home/csgo/hlserver/csgo:/home/csgo/hlserver/csgo/bin:
Failed to open libtier0.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
Add "-debug" to the /home/csgo/hlserver/csgo/srcds_run command line to generate a debug.log to help with solving this problem
Tue Feb 28 19:58:22 UTC 2023: Server restart in 10 seconds
```

**Comment by War3Evo** [comment]
looks like you need either libtier0.so or libstdc++.so.6 library

**Comment by War3Evo** [comment]
https://steamcommunity.com/app/222880/discussions/2/618457398958286048/

**Comment by War3Evo** [comment]
what's your output for `ldd --version`

**Comment by You-Honey** [comment]
This command fixed it: `sudo apt-get install lib32stdc++6`

**Comment by You-Honey** [comment]
I was able to join the server. Here's the full startup log with few errors:

[result-success.txt](https://github.com/War3Evo/War3Source-EVO/files/10854471/result-success.txt)

Errors I noticed:

1. `/home/csgo/hlserver/csgo/srcds_run: 32: pushd: not found`
2. `/home/csgo/hlserver/csgo/srcds_run: 35: popd: not found`
3. `/home/csgo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory`
4. Unkown commands:
```
Unknown command "cl_bobamt_vert"
Unknown command "cl_bobamt_lat"
Unknown command "cl_bob_lower_amt"
Unknown command "cl_viewmodel_shift_left_amt"
Unknown command "cl_viewmodel_shift_right_amt"
Unknown command "cl_teamid_min"
Unknown command "cl_teamid_max"
Unknown command "cl_teamid_overhead"
Unknown command "cl_teamid_overhead_maxdist"
Setting mapgroup to 'mg_active'
Unknown command "port"
```
5. `exec: couldn't exec gamemode_casual_server.cfg`
6. `Commentary: Could not find commentary data file 'maps/de_dust2_commentary.txt'.`
7. `Error parsing BotProfile.db - unknown attribute 'Rank'`
8. The War3Evo mode is not on.

**Comment by War3Evo** [comment]
do you have Discord... this is better on discord.

[https://discord.com/invite/uhTfXYgJfB](https://discord.com/invite/uhTfXYgJfB)

**Comment by War3Evo** [comment]
does the server even start up?

in the server console.. .have you tried:

`meta version`
 Metamod:Source Version Information
    Metamod:Source version 1.11.0-dev+1148
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Jun 26 2022 08:02:30
    Built from: https://github.com/alliedmodders/metamod-source/commit/4bdc218
    Build ID: 1148:4bdc218
    http://www.metamodsource.net/
`sm version`
 SourceMod Version Information:
    SourceMod Version: 1.11.0.6931
    SourcePawn Engine: 1.11.0.6931, jit-x86 (build 1.11.0.6931)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Feb 12 2023 18:17:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/99a99484
    Build ID: 6931:99a99484
    http://www.sourcemod.net/
`war3e_version`
"war3e_version" = "2.18.2023.2.28.PM.EST by El Diablo"
 notify singleplayer
 - War3Source:EVO version.

**Comment by You-Honey** [comment]
I joined the discord. You are `El Diablo` I assume?

**Comment by War3Evo** [comment]
yes... join #war3source-evo      in discord and discuss there.  Yes I'm El Diablo

**Comment by War3Evo** [comment]
Lesson learned == reinstall using same script.  It will not download steam server twice, it will skip that and try to download war3evo's war3source via git and compile it again.

If you ever have bugs... some reason the server doesn't install correctly... un comment out some of the sudo apt-get install lines in the script... then try the script again.
