### ISSUE TITLE
Cant compile nightelf

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [War3Evo/War3Source-EVO#4]
War3Source_004_NightElf.sp
For CSGO

War3Source_004_NightElf.sp(389) : error 105: cannot find method or property ThisRacePlayer.trulyalive
War3Source_004_NightElf.sp(408) : error 105: cannot find method or property ThisRacePlayer.flashscreen
War3Source_004_NightElf.sp(445) : error 105: cannot find method or property ThisRacePlayer.flashscreen
War3Source_004_NightElf.sp(474) : error 105: cannot find method or property ThisRacePlayer.flashscreen

4 Errors.

**Comment by War3Evo** [comment]
fixed by uploading new war3source.ini file
