### ISSUE TITLE
Invis not working

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [War3Evo/War3Source-EVO#6]
Invis does not work as human nor does the cloak of shadows seem to work. :/

CSGO

**Comment by War3Evo** [comment]
Please report platform

**Comment by War3Evo** [comment]
Fix found in these links:

https://github.com/War3Source/War3Source/blob/0d1b91ff594af238f1dc83f49c29f503806463c7/addons/sourcemod/scripting/War3Source_Engine_BuffSpeedGravGlow.sp#L30-L42

https://github.com/War3Source/War3Source/blob/0d1b91ff594af238f1dc83f49c29f503806463c7/addons/sourcemod/scripting/War3Source_Engine_BuffSpeedGravGlow.sp#L81-L92

And will probably have to search through different sources for the rest.
